[Settings]
language = en
folder = ~/Pictures/Wallpapers
; 显示器设置，All表示所有显示器，Primary表示主显示器，Secondary表示次显示器，或者直接指定显示器名称 如HDMI-A-1
monitors = All
wallpaper = ~/Pictures/Wallpapers/wall_1769769387.png
show_path_in_tooltip = True
backend = swww
; 适用于swww的填充方式，stretch表示拉伸，center表示居中，tile表示平铺，fill表示填充
fill = fill
; 壁纸排序方式，daterev表示按日期倒序，date表示按日期正序，name表示按名称排序，random表示随机排序
sort = daterev
color = #ffffff
subfolders = False
all_subfolders = False
show_hidden = False
show_gifs_only = False
zen_mode = True
post_command = $HOME/.config/scripts/matugen-update.sh $wallpaper && sleep 0.8 && $HOME/.config/scripts/niri_set_overview_blur_dark_bg.sh $wallpaper
number_of_columns = 3
swww_transition_type = any
swww_transition_step = 63
swww_transition_angle = 0
swww_transition_duration = 3
swww_transition_fps = 60
mpvpaper_sound = False
mpvpaper_options = 
; 不使用 XDG 状态目录来保存应用状态，而是直接使用本地配置
use_xdg_state = False
stylesheet = /home/daguo/.config/waypaper/style.css

